services:
  user_postgres:
    image: postgres:16
    container_name: user_postgres
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${USER_DB_PORT_FORWARD}:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${USER_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

  chat_postgres:
    image: postgres:16
    container_name: chat_postgres
    environment:
      POSTGRES_DB: ${CHAT_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${CHAT_DB_PORT_FORWARD}:5432"
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${CHAT_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

  redis:
    image: redis:7-alpine
    container_name: chat_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - chat-network

#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: chat_rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#    healthcheck:
#      test: ["CMD", "rabbitmq-diagnostics", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - chat-network

  user_service:
    build: ./user-service
    container_name: user_service
    depends_on:
      user_postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${USER_HTTP_PORT}:${HTTP_PORT}"
      - "${USER_GRPC_PORT}:${GRPC_PORT}"
    networks:
      - chat-network

  chat_service:
    build: ./chat-service
    container_name: chat_service
    depends_on:
      chat_postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    #      rabbitmq:
    #        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${CHAT_HTTP_PORT}:${HTTP_PORT}"
      - "${CHAT_GRPC_PORT}:${GRPC_PORT}"
    networks:
      - chat-network

volumes:
  user_postgres_data:
  chat_postgres_data:
  redis_data:
#  rabbitmq_data:

networks:
  chat-network:
    driver: bridge
